---
title: "Working with Models"
output: html_document
---

[`ramp.uganda`](../index.html)

***


```{r}
library(ramp.xds)
library(dplyr)
library(ramp.uganda)
library(ramp.work)
attach(yaml::read_yaml("../my_paths.yaml")) 
``` 

This sets locations for `Box/RAMP` and `ramp.uganda` 



```{r}
FirstYear <-2015
irs_time <- list()
no_irs <- c()

for (j in dist_name) {
  dates <- get_irs_jdates(j, FirstYear)

  if (!is.null(dates) && length(dates) > 0 && any(dates > 0)) {
    irs_time[[j]] <- sort(dates[dates > 0])
  } else {
    no_irs <- c(no_irs, j)
  }
}
```
Get fitted models to pfpr data for all the irs_district

```{r}
irs_dist <- list()
for (i in 1:35)
  irs_dist[[i]]<- names(irs_time)[i]
```

```{r, eval=F}
directory <- paste(box_dir, "models", sep = "") 
eir_files <- list.files(path = directory, pattern = "*_eir_sis.rds", full.names = TRUE)
clean_name <- function(name) {
  tolower(gsub(" ", "_", name))
}
cleaned_dists <- sapply(irs_dist, clean_name)
# Find indices in eir_files that contain each cleaned district name
matched_indices <- sapply(cleaned_dists, function(dname) {
  which(grepl(dname, eir_files))
})

eir_files_irs <- eir_files[matched_indices]
```


Get pfpr data by district 
```{r,eval=F}
load("C:/Users/Admin/Documents/ramp.uganda/data/district_dir.rda")
#load("C:/Users/doree/Documents/Github/ramp.uganda/data/district_dir.rda")
#dist_name <-irs_dist
data_list = list()
for(i in irs_dist)
  data_list[[i]] <- get_district_pfpr(i)
```


```{r, eval=F}
fitted_mod <- list()
for (i in 1:length(irs_dist)) {
  fitted_mod[[i]] <- readRDS(eir_files_irs[i])
}
```



## District Baseline

```{r, fig.height=8, fig.width=11}
profile_irs = function(i, model_list, data_list){
  mod_file <- model_list[[i]]
  data <- data_list[[i]]

  ix <- unique(sapply(irs_time[[i]], function(x) {
  idx <- which(fitted_mod[[i]]$EIRpar$trend_par$tt > x)
  if (length(idx) > 0) return(idx[1]) else return(NA)
}))
  cf_max <- make_cf_base_max(ix, mod_file)
  cf_min <- make_cf_base_min(ix, mod_file)
  cf_median <- make_cf_base_median(ix, mod_file)
  cf_mean <- make_cf_base_mean(ix, mod_file)
  mod1a <- modify_baseline(mod_file, cf_max) 
  mod1b <- modify_baseline(mod_file, cf_min) 
  mod1c <- modify_baseline(mod_file, cf_median) 
  mod1d <- modify_baseline(mod_file, cf_mean) 
  vals <- get_XH(mod_file)
  vals1a <- get_XH(mod1a)
  vals1b <- get_XH(mod1b)
  vals1c <- get_XH(mod1c)
  vals1d <- get_XH(mod1d)

  with(vals1a, plot(time/365+FirstYear, true_pr, ylab = "PR",lwd=2, xlab = "Time", main=unique(data$district_name), type = "l", ylim = c(0,1), col="darkred"))
  with(vals1b, lines(time/365+FirstYear, true_pr,  lwd=2, col="darkgreen"))
  with(vals1c, lines(time/365+FirstYear, true_pr, lwd=2,  col="purple4"))
  with(vals1d, lines(time/365+FirstYear, true_pr, lwd=2,  col="darkorange"))
  with(vals, lines(time/365+FirstYear, true_pr, lwd=2,  col="darkblue"))
  with(data, lines(jdate/365+FirstYear, pfpr, pch=16,type = "o", col="darkblue"))
#par(xpd = TRUE, mar = c(5, 4, 4, 2))  # allow plotting outside
  legend("topleft",  c("max", "min","median","mean"), # Names for the groups   , 
  col = c("darkred", "darkgreen","purple4","darkorange"),
  lwd=2, pch=c(NA,NA,NA,NA,16), horiz = FALSE, bty="n")      
 add_irs_history(unique(data$district_name))
     

  ## -------------Effect Size--------------------------------------------------------------------------
  max_eff <- vals1a$true_pr
  min_eff <- vals1b$true_pr
  median_eff <- vals1c$true_pr
  mean_eff <- vals1d$true_pr
  base <- vals$true_pr

  max_effless <- max_eff[1:(length(max_eff) - 3)]/base
 
 min_effless <- min_eff[1:(length(min_eff)-3 )]/base
 median_effless <- median_eff[1:(length(median_eff)-3 )]/base
 mean_effless <- mean_eff[1:(length(mean_eff) - 3)]/base
 
 ## _____________________________________________________________________________________________________________________
 t_time <- mod_file$outputs$time
  # Initialize
closest_index1 <- NA
closest_index2 <- NA
index_seq <- integer(0)

# Ensure this block runs only if there are irs times
if (length(irs_time[[i]]) > 0 && length(t_time) > 0) {
  
  if (length(irs_time[[i]]) < 3) {
    # Use only the most recent irs time
    irs_1 <- tail(irs_time[[i]], 1)
    closest_index1 <- which.min(abs(t_time - irs_1))

    # Define interval up to 12 months after irs_1
    t_limit <- irs_1 + 12
    closest_index2 <- which.min(abs(t_time - t_limit))
    
  } else {
    # Use last 3 irs times
    irs_1 <- irs_time[[i]][length(irs_time[[i]]) - 2]
    irs_2 <- irs_time[[i]][length(irs_time[[i]]) - 1]
    irs_3 <- tail(irs_time[[i]], 1)
    
    closest_index1 <- which.min(abs(t_time - irs_1))
    closest_index2 <- which.min(abs(t_time - irs_2))
    closest_index3 <- which.min(abs(t_time - irs_3))  # optional
  }

  # Safely compute sequence if indices are valid
  if (!is.na(closest_index1) && !is.na(closest_index2)) {
    index_seq <- closest_index1:closest_index2
  }
}

#_____________________________________________________________________________________________________________  
  # create a data frame for the effect sizes
  
  Effect_table <- data.frame(
  irs_Type = c("IRS1","IRS2","IRS3" ),
  max_effect = round(c(mean(max_effless[closest_index1:closest_index2]), mean(max_effless[closest_index2:closest_index3]), mean(max_effless[closest_index3:length(t_time)])),2),
  min_effect = round(c(mean(min_effless[closest_index1:closest_index2]), mean(min_effless[closest_index3:closest_index3]), mean(min_effless[closest_index3:length(t_time)])),2),
  median_effect = round(c(mean(median_effless[closest_index1:closest_index2]), mean(median_effless[closest_index3:closest_index3]), mean(median_effless[closest_index3:length(t_time)])),2),
  mean_effect = round(c(mean(mean_effless[closest_index1:closest_index2]), mean(mean_effless[closest_index3:closest_index3]), mean(mean_effless[closest_index3:length(t_time)])),2),
  
  max_percent = round(c((1 - (1 / mean(max_effless[closest_index1:closest_index2]))) * 100, (1 - (1 / mean(max_effless[closest_index2:closest_index3]))) * 100, (1 - (1 / mean(max_effless[closest_index3:length(t_time)]))) * 100),2),
  min_percent = round(c((1 - (1 / mean(min_effless[closest_index1:closest_index2]))) * 100, (1 - (1 / mean(min_effless[closest_index2:closest_index3]))) * 100, (1 - (1 / mean(min_effless[closest_index3:length(t_time)]))) * 100),2),
  median_percent = round(c((1 - (1 / mean(median_effless[closest_index1:closest_index2]))) * 100, (1 - (1 / mean(median_effless[closest_index2:closest_index3]))) * 100, (1 - (1 / mean(median_effless[closest_index3:length(t_time)]))) * 100),2),
  mean_percent = round(c((1 - (1 / mean(mean_effless[closest_index1:closest_index2]))) * 100, (1 - (1 / mean(mean_effless[closest_index2:closest_index3]))) * 100, (1 - (1 / mean(mean_effless[closest_index3:length(t_time)]))) * 100),2))

  #-------------------------------------------------------------------------------------------------------------------------------
  
   plot(mod_file$outputs$time/365+FirstYear,max_effless, type= "l",lwd= 2, col="darkred" , main=unique(data$district_name), xlab = "Time", ylab = "Effect Sizes", ylim = c(0, max(max_effless)) )
  lines(mod_file$outputs$time/365+FirstYear,min_effless , lwd= 2, col="darkgreen")
  lines(mod_file$outputs$time/365+FirstYear,median_effless, lwd= 2, col="purple4" )
  lines(mod_file$outputs$time/365+FirstYear,mean_effless, lwd= 2, col="darkorange" )
  add_irs_history(unique(data$district_name))
  legend("topleft",    #inset=-0.2 ,              # Position of the legend
  legend = c(
          paste0(
  "max_effs: ", sprintf("%.2f", mean(max_effless[closest_index3:length(t_time)], na.rm = TRUE)),
  " (", sprintf("%.2f%%", (1 - (1 / mean(max_effless[closest_index3:length(t_time)], na.rm = TRUE))) * 100)," reduction)")
,
paste0("min_effs: ", sprintf("%.2f", mean(min_effless[closest_index3:length(t_time)], na.rm = TRUE)),
  " (", sprintf("%.2f%%", (1 - (1 / mean(min_effless[closest_index3:length(t_time)], na.rm = TRUE))) * 100),")")
,
paste0("median_effs: ", sprintf("%.2f", mean(median_effless[closest_index3:length(t_time)], na.rm = TRUE)),
  " (", sprintf("%.2f%%", (1 - (1 / mean(median_effless[closest_index3:length(t_time)], na.rm = TRUE))) * 100),")"
),
 paste0( "mean_effs: ", sprintf("%.2f", mean(mean_effless[closest_index3:length(t_time)], na.rm = TRUE)),
  " (", sprintf("%.2f%%", (1 - (1 / mean(mean_effless[closest_index3:length(t_time)], na.rm = TRUE))) * 100),")")),
  col = c("darkred", "darkgreen","purple4","darkorange"),
  lwd=2, pch=c(NA,NA,NA,NA,16), horiz = FALSE, bty="n") 
  
  
  return(data.frame(
      district_name = unique(data$district_name),
      Effect_table
      )
    )


  

  }

```

```{r}
#pdf("irs_districts_cts.pdf")
#for(i in 1:length(irs_dist))
 # profile_irs(i, fitted_mod, data_list)
#dev.off()
#---------------------------------------------------------------------------------------------------------------------------------
#pdf("PBO_districts_cts_only.pdf")
malaria_irs_Effect <- list()
for(i in 1:length(irs_dist) ) {
#for (i in setdiff(1:length(dist_name), c(10,27,33,35.37,42,86,95,98,99,101,140)))  {
  irs <- profile_irs(i, fitted_mod, data_list)  
  malaria_irs_Effect[[i]] <- irs  # Store each data.frame
}
#dev.off()
# Combine all stored data.frames into one big data.frame
malaria_irs_eff <- do.call(rbind, malaria_irs_Effect)
# Save to CSV
write.csv(malaria_irs_eff, "../data/irs_not_cts_eff.csv", row.names = FALSE)
```
```

