---
title: "Uganda Districts"
output: html_document
---

```{r}
library(chron)
library(ramp.work)
```
```{r}
BoxModels <- "/Users/smitdave/Library/CloudStorage/Box-Box/RAMP/Models/"
```

```{r}
abim <- readRDS("/Users/smitdave/Library/CloudStorage/Box-Box/RAMP/Models/abim_district_eir_sis.rds")
```

```{r}
agago <- readRDS("/Users/smitdave/Library/CloudStorage/Box-Box/RAMP/Models/agago_district_eir_sis.rds")
```



```{r}
dist_dir <- read.csv("../data/district_directories.csv")
city_dir <- read.csv("../data/city_directories.csv")
```


```{r}
start = as.Date("2015-01-01")
pfpr_by_district <- read.csv("../data/pfpr_ts_district_from_hf_pixel_agg.csv", header=TRUE)
pfpr_by_district$date <- as.Date(pfpr_by_district$date)
pfpr_by_district$jdate <- julian(pfpr_by_district$date, origin = start) 
```

```{r}
yr0 = min(pfpr_by_district$year) 
yrN = max(pfpr_by_district$year) + 1 
```

```{r}
get_pfpr_ts = function(district, data){
   ix <- which(data$district_name == district)
   tmp <- data[ix,]
   ot <- order(tmp$jdate)
   return(tmp[ot,]) 
}

plot_pr = function(district, data){
  dist_data <- get_pfpr_ts(district, data)
  mnyr = min(dist_data$year) 
  mxyr = max(dist_data$year)+1
  yrs = c(mnyr:mxyr)
  with(dist_data, {
       plot(jdate, pfpr, type = "b", ylim = c(0,1), xlim = range(0, jdate), xaxt="n", xlab = "Date", ylab = "Pf`PR")
       axis(1, 365*(yrs-mnyr), yrs) 
    }) 
}
```


```{r}
plot_pr("Abim District", pfpr_by_district)
```
## Write to Box 


## EIR History 

```{r}
eir_by_district = function(data, mod){
  mod_fit <- pr2eir_history(data$pfpr, data$jdate, mod)
  mod_fit <- xds_solve_cohort(mod_fit, times = seq(0, max(data$jdate), by = 10))
  return(mod_fit)  
}
```


```{r}
eir_fit_save_i = function(i, data, model, district_names){
  district <- district_names$district_name[i]
  model$location <- district_names$stem[i]
  prts <- get_pfpr_ts(district, data)
#  fit_eir <- pr2eir_history(prts$pfpr, prts$jdate, mod)
#  fit_eir <- xds_solve_cohort(fit_eir, times = seq(0, max(prts$jdate), by = 10))
  fit_eir <- model
  write_model_to_box(fit_eir)
}
```

```{r}
#abim_eir$location <- dist_dir$stem[1] 
write_model_to_box(abim_eir)
```


```{r}
mod <- xds_setup_cohort(model_name = "sis_test")
```

```{r}
abim <- get_pfpr_ts("Abim District", pfpr_by_district)
abim_eir <- eir_by_district("Abim District", pfpr_by_district, mod)
```


```{r}
eir_fit_save_i(1, pfpr_by_district, mod, dist_dir)
```

```{r}
abim_eir1 <- readRDS("../models/abim_district_eir_model.rds")
```

```{r}
plot_pr("Abim District", pfpr_by_district)
xds_plot_PR(abim_eir, add = TRUE, clrs = "darkred")
xds_plot_PR(abim_eir1, add = TRUE, clrs = "darkblue")
```

## Lambda History 

```{r}
Lambda_by_district = function(district, data, mod){
  prts <- get_pfpr_ts(district, data)
  mod_fit <- pr2Lambda_history(prts$pfpr, prts$jdate, mod)
  mod_fit <- xds_solve(mod_fit, times = seq(0, max(prts$jdate), by = 10))
  return(mod_fit)  
}
```

```{r}
Lambda_fit_save_i = function(i, data, mod, dir){
   district <- dir[i,1] 
   filename <- paste("../models/", dir[i,2], "_Lambda_model.rds", sep="") 
   fit_Lambda <- Lambda_by_district(district, data, mod)
   saveRDS(fit_Lambda, filename) 
}
```

```{r}
mod_Lambda <- xds_setup()
mod_Lambda$Lpar[[1]]$season_par <- makepar_F_sin() 
mod_Lambda$Lpar[[1]]$trend_par <- makepar_F_spline(c(0:9)*365, rep(1,10)) 
```

```{r}
abim_Lambda <- Lambda_by_district("Abim District", pfpr_by_district, mod_Lambda)
```

```{r}
Lambda_fit_save_i(1, pfpr_by_district, mod_Lambda, dist_dir)
```

```{r}
abim_Lambda1 <- readRDS("../models/abim_district_Lambda_model.rds")
```

```{r}
plot_pr("Abim District", pfpr_by_district)
xds_plot_PR(abim_Lambda, add = TRUE, clrs = "darkred")
xds_plot_PR(abim_Lambda1, add = TRUE, clrs = "darkblue")
```
