---
title: "Effect Size Estimation Pakwach" 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document 
vignette: >
  %\VignetteIndexEntry{Effect Size Estimation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
suppressMessages(library(dplyr))
suppressMessages(library(ramp.xds))
suppressMessages(library(ramp.work))
suppressMessages(library(ramp.control))
suppressMessages(library(ramp.library))
suppressMessages(library(ramp.uganda))
```


#Reading in the data
```{r}
#tprdata <- read.csv(file='C:/Users/Admin/Documents/ramp.uganda/data-raw/pfpr_ts_district_from_hf_pixel_agg.csv')
tprdata <- read.csv(file='C:/Users/doree/Documents/Github/ramp.uganda/data-raw/pfpr_ts_district_from_hf_pixel_agg.csv')
sorted_data <- tprdata[order(tprdata$district_name,tprdata$period),] #arrange the data in chronical order of period and district name
base_data1 <-sorted_data[sorted_data$period >= 201506 & sorted_data$period <= 201701, ]
base_data2 <-sorted_data[sorted_data$period >= 201506 & sorted_data$period <= 202101, ]
base_data3 <-sorted_data[sorted_data$period >= 201506 & sorted_data$period <= 202212, ]
id_name= sorted_data$district_name
id_name1 = base_data1$district_name
id_name2 = base_data2$district_name
id_name3 = base_data3$district_name
dist_name1 = unique(base_data1$district_name)
dist_name2 = unique(base_data2$district_name)
dist_name3 = unique(base_data3$district_name)
dist_namef= unique(sorted_data$district_name)
```

## ----get_one_district baseline data------------------------------------
```{r}
get_one_district_base1 = function(i){
  # Pull PfPR values
  pfpr <- as.vector(base_data1 %>% filter(id_name1 == dist_name1[i]) %>% select(pfpr))$pfpr
    # Pull and convert month year to date
  t_start =2015
  period <- as.vector(base_data1 %>% filter(id_name1 == dist_name1[i]) %>% select(period))$period
  year <- as.numeric(substr(period, 1, 4))  # Extract first 4 characters
  month <- as.numeric(substr(period, 5, 6))  # Extract last 2 characters
  fac_time_month = (year+month/12) # TIME IN months
  fac_time_day = (fac_time_month-t_start)*365 -15 # time in days
  list(pr = pfpr, times = fac_time_day, name = dist_name1[i])
}
```


```{r}
get_one_district_base2 = function(i){
  # Pull PfPR values
  pfpr <- as.vector(base_data2 %>% filter(id_name2 == dist_name2[i]) %>% select(pfpr))$pfpr
    # Pull and convert month year to date
  t_start =2015
  period <- as.vector(base_data2 %>% filter(id_name2 == dist_name2[i]) %>% select(period))$period
  year <- as.numeric(substr(period, 1, 4))  # Extract first 4 characters
  month <- as.numeric(substr(period, 5, 6))  # Extract last 2 characters
  fac_time_month = (year+month/12) # TIME IN months
  fac_time_day = (fac_time_month-t_start)*365 -15 # time in days
  list(pr = pfpr, times = fac_time_day, name = dist_name1[i])
}
```

```{r}
get_one_district_base3 = function(i){
  # Pull PfPR values
  pfpr <- as.vector(base_data3 %>% filter(id_name3 == dist_name3[i]) %>% select(pfpr))$pfpr
    # Pull and convert month year to date
  t_start =2015
  period <- as.vector(base_data3 %>% filter(id_name3 == dist_name3[i]) %>% select(period))$period
  year <- as.numeric(substr(period, 1, 4))  # Extract first 4 characters
  month <- as.numeric(substr(period, 5, 6))  # Extract last 2 characters
  fac_time_month = (year+month/12) # TIME IN months
  fac_time_day = (fac_time_month-t_start)*365 -15 # time in days
  list(pr = pfpr, times = fac_time_day, name = dist_name3[i])
}
```


## ----get_one_district full data ------------------------------------
```{r}
get_one_district = function(i){
  # Pull PfPR values
  pfpr <- as.vector(sorted_data %>% filter(id_name == dist_name[i]) %>% select(pfpr))$pfpr
  # Pull and convert month year to date
  t_start =2015
  period <- as.vector(sorted_data %>% filter(id_name == dist_name[i]) %>% select(period))$period
  year <- as.numeric(substr(period, 1, 4))  # Extract first 4 characters
  month <- as.numeric(substr(period, 5, 6))  # Extract last 2 characters
  fac_time_month = (year+month/12) # TIME IN months
  fac_time_day = (fac_time_month-t_start)*365 -15 # time in days
  list(pr = pfpr, times = fac_time_day, name = dist_name[i])
}
```

# Setting the ITN start time

```{r}

t_start =2015
year1 <- as.numeric(substr(201701, 1, 4))  # Extract first 4 characters
month1 <- as.numeric(substr(201701, 5, 6))  # Extract last 2 characters
fac_time_month1 = (year1+month1/12) # TIME IN months
itn_starttime1 = (fac_time_month1-t_start)*365 -15 # time in days

year2 <- as.numeric(substr(202101, 1, 4))  # Extract first 4 characters
month2 <- as.numeric(substr(202101, 5, 6))  # Extract last 2 characters
fac_time_month2 = (year2+month2/12) # TIME IN months
itn_starttime2 = (fac_time_month2-t_start)*365 -15 # time in days

year3 <- as.numeric(substr(202212, 1, 4))  # Extract first 4 characters
month3 <- as.numeric(substr(202212, 5, 6))  # Extract last 2 characters
fac_time_month3 = (year3+month3/12) # TIME IN months
itn_starttime3 = (fac_time_month3-t_start)*365 -15 # time in days
```

#-------------------------------------full model time fit --------------------------------------------
```{r}
data_list = list()
for(i in 128)
  data_list[[i]] <- get_one_district(i)
 
``` 

#-------------------------------- base model time fit---------------------------------------------------------
```{r}
data_list_base1 <- list()
data_list_base2 <- list()
data_list_base3 <- list()
for(i in 128)
  data_list_base1[[i]] <- get_one_district_base1(i)
  data_list_base2[[i]] <- get_one_district_base2(i)
  data_list_base3[[i]] <- get_one_district_base3(i)
```

#--------------------------------------------------------------------------------------------------------
```{r}
fit_one_district_base1 = function(i, model){
    with(data_list_base1[[i]],
         return(pr2eir_history(pr, times, model))
 )}
fit_one_district_base2 = function(i, model){
    with(data_list_base2[[i]],
         return(pr2eir_history(pr, times, model))
 )}
fit_one_district_base3 = function(i, model){
    with(data_list_base3[[i]],
         return(pr2eir_history(pr, times, model))
 )}
```


#----------------------pre control baseline---------------------------------------------------  \

```{r}
fitted_models=list() 

Xo = list(xi=1/365, rho=0.2)
model <- xds_setup_cohort(Xname= "SIP", Xopts = Xo, F_season = make_function(makepar_F_sin()))

```

```{r}  
directory <- paste("C:/Users/doree/Box/RAMP", "/models", sep = "") 
eir_files <- list.files(path = directory, pattern = "*_eir_sis.rds", full.names = TRUE)
  
```

## ----fit_all_district--------------------------------------------------------------------------------------

```{r}
fitted_models1 <- list()
fitted_models2 <- list()
fitted_models3 <- list()
fitted_mod <- list()
# Loop through each RDS file and load it into the list
for (i in 128) {
    fitted_models1[[i]] <- fit_one_district_base1(i, model)
    fitted_models2[[i]] <- fit_one_district_base2(i, model)
    fitted_models3[[i]] <- fit_one_district_base3(i, model)
    fitted_mod[[i]] <- readRDS(eir_files[i])
  }
```  
  
## -----------Set up plotting profile---------------------------------------------------------------------------
```{r}
FirstYear = 2015.5
profileL = function(i, fitted_models, data_list_base,fitted_mod, data_list){
  #FirstYear = 2016
  
  mod1 <- fitted_models1[[128]]
  mod2 <- fitted_models2[[128]]
  mod3 <- fitted_models3[[128]]
  mod_full <- fitted_mod[[128]]
  
  data1 <- data_list_base1[[128]]
  data2 <- data_list_base2[[128]]
  data3 <- data_list_base3[[128]]
  data_full <- data_list[[128]]

  tt1 <- seq(-90, ceiling(max(data1$times)/365)*365-90 , length.out=200)
  tt2 <- seq(-90, ceiling(max(data2$times)/365)*365-90 , length.out=200)
  tt3 <- seq(-90, ceiling(max(data3$times)/365)*365-90 , length.out=200)
  tt_full<- seq(-90, ceiling(max(data_full$times)/365)*365-90 , length.out=200)
  tt_foc1 <- seq(-90, ceiling(max(data1$times)/365)*365-90+5*365 , length.out=200)
  tt_foc2 <- seq(-90, ceiling(max(data2$times)/365)*365-90+5*365 , length.out=200)
  tt_foc3 <- seq(-90, ceiling(max(data3$times)/365)*365-90+5*365 , length.out=200)
  
  mod1 <- xds_solve_cohort(mod1, times=tt1)
  get_XH(mod1) -> vals1
  mod2 <- xds_solve_cohort(mod2, times=tt2)
  get_XH(mod2) -> vals2
  mod3 <- xds_solve_cohort(mod3, times=tt3)
  get_XH(mod3) -> vals3
  
  mod_full <- xds_solve_cohort(mod_full, times=tt_full)
  get_XH(mod_full) -> vals_full
  
  baselinevals1 <- vector("list", 10)
  baselinevals2 <- vector("list", 10)
  baselinevals3 <- vector("list", 10)
  
  for (j in 1:10) {
    mod11 <- forecast_spline_EIR(mod1, 5, x_last = 0)
    mod11 <- xds_solve_cohort(mod11, times = tt_foc)
    vals11 <- get_XH(mod11)
    baselinevals1[[j]] <- vals11$true_pr
    
    mod21 <- forecast_spline_EIR(mod2, 5, x_last = 0)
    mod21 <- xds_solve_cohort(mod21, times = tt_foc)
    vals21 <- get_XH(mod21)
    baselinevals2[[j]] <- vals21$true_pr
    
    mod31 <- forecast_spline_EIR(mod3, 5, x_last = 0)
    mod31 <- xds_solve_cohort(mod31, times = tt_foc)
    vals31 <- get_XH(mod31)
    baselinevals3[[j]] <- vals31$true_pr
    
   }
  # baselinevals is a list of numeric vectors of equal length
  median_list1 <- apply(do.call(rbind, baselinevals1), 2, median)
  median_list2 <- apply(do.call(rbind, baselinevals2), 2, median)
  median_list3 <- apply(do.call(rbind, baselinevals3), 2, median)
  
  mean_list1 <- Reduce("+", baselinevals1) / length(baselinevals1)
  mean_list2 <- Reduce("+", baselinevals2) / length(baselinevals2)
  mean_list3 <- Reduce("+", baselinevals3) / length(baselinevals3)
  
  max_list1 <- apply(do.call(rbind, baselinevals1), 2, max)
  max_list2 <- apply(do.call(rbind, baselinevals2), 2, max)
  max_list3 <- apply(do.call(rbind, baselinevals3), 2, max)
  
  closest_index1 <- which.min(abs(vals_full$time - itn_starttime1))
  closest_index2 <- which.min(abs(vals_full$time - itn_starttime2))
  closest_index3 <- which.min(abs(vals_full$time - itn_starttime3))
  
  
  effectsize_median <- ((median_list1[closest_index1:length(vals_full$time)] - vals_full$true_pr[closest_index1:length(vals_full$time)])/median_list1[closest_index1:length(vals_full$time)])*100
  effectsize_mean <- ((mean_list1[closest_index1:length(vals_full$time)] - vals_full$true_pr[closest_index1:length(vals_full$time)])/mean_list1[closest_index1:length(vals_full$time)])*100
  effectsize_max <- ((max_list1[closest_index1:length(vals_full$time)] - vals_full$true_pr[closest_index1:length(vals_full$time)])/max_list1[closest_index1:length(vals_full$time)])*100
  
  #par(mfrow = c(2, 1))
  with(vals_full, plot(time/365+FirstYear, true_pr, ylab = "PR", lwd=2, xlab = "Time", main = data$name, type = "l", ylim = c(0,1),col="black")) #model fit for full data
  lines(vals11$time/365 + FirstYear, max_list1, lwd = 2, col="purple")# forcat after 2018_dec
  lines(vals11$time/365 + FirstYear, mean_list1, lwd = 2, col="red")# forcat after 2018_dec
  lines(vals11$time/365 + FirstYear, median_list1, lwd = 2, col="green")# forcat after 2018_dec
  #with(vals, lines(time/365+FirstYear, true_pr, lwd=2, col="darkblue"))# model fit from 2015-2018 dec
  with(data_full, lines(data_full$times/365+FirstYear, pr, pch=19,type = "o", col="darkblue")) #full data plot
  
  #inset=-0.2 
  #par(xpd = TRUE, mar = c(5, 4, 4, 2))  # allow plotting outside
  legend("topleft",              # Position of the legend
         legend = c("fitted model", "max baseline","mean baseline","median baseline","pfpr data"), # Names for the groups
         col = c("black", "purple","red","green","darkblue"),
         lwd=2, pch=c(NA,NA,NA,NA,19), horiz = FALSE, bty="n")      # Colors corresponding to the groups
  
  plot(FirstYear + (vals_full$time[closest_index1:length(vals_full$time)])/365,effectsize_median, ylab = "Effect sze", lwd=2, xlab = "Time", type = "l",col="green" )
  lines(FirstYear + (vals_full$time[closest_index1:length(vals_full$time)])/365,effectsize_mean, lwd=2, col="red")
  lines(FirstYear + (vals_full$time[closest_index1:length(vals_full$time)])/365,effectsize_max, lwd=2, col ="purple")
  
  legend("bottomright",              # Position of the legend
         legend = c(
           paste0("median_effs: ", sprintf("%.2f%%", median(effectsize_median))),
           paste0("mean_effs: ", sprintf("%.2f%%", mean(effectsize_median))),
           paste0("max_effs: ", sprintf("%.2f%%", max(effectsize_median)))
         ),
         col = c("green", "red", "purple"),
         lwd = 2,
         horiz = FALSE,
         bty = "n")
  
  
  # Symbols for the groups
  # return(list(
  #   name = data$name,
  #   baseline = baselinevals,
  #   fit_vals = vals,
  #   full_fit_vals = vals_full,
  #   forecast_vals = vals1
  # ))
  
}
```

```{r}
pdf("C:/Users/doree/Documents/Github/Doreen/ramp_uganda_files/Pakwach_effectsize1.pdf")
for(i in 128)
  profileL(i, fitted_models, data_list_base, fitted_mod, data_list)
dev.off(dev.cur())
```

