---
title: "Working with Models"
output: html_document
---

[`ramp.uganda`](../index.html)

***


```{r}
library(ramp.xds)
library(dplyr)
library(ramp.uganda)
library(ramp.work)
library(ramp.library)
attach(yaml::read_yaml("../my_paths.yaml")) 
``` 

This sets locations for `Box/RAMP` and `ramp.uganda` 

```{r, eval=F}
directory <- paste(box_dir, "models", sep = "") 
eir_files <- list.files(path = directory, pattern = "*_eir_sis.rds", full.names = TRUE)
head(eir_files, 2)
```

```{r, eval=F}
fitted_mod <- list()
for (i in 1:146) {
  fitted_mod[[i]] <- readRDS(eir_files[i])
}
```

```{r, eval=F}
data_list = list()
for(i in 1:146)
  data_list[[i]] <- get_one_district(i)
```

```{r}
FirstYear <-2015
irs_time <- get_irs_jdates("Madi-Okollo District", 2015)
sort(irs_time)

```



```{r, fig.height=8, fig.width=11}
mod_file <- fitted_mod[[92]] #madi-Okollo
#tt_irs <- mod_file$EIRpar$trend_par$tt
ix = c(10,11,12)
cf_max <- make_cf_base_max(ix, mod_file)
cf_min <- make_cf_base_min(ix, mod_file)
cf_median <- make_cf_base_median(ix, mod_file)
cf_mean <- make_cf_base_mean(ix, mod_file)
```

```{r}
mod1a <- modify_baseline(mod_file, cf_max) 
mod1b <- modify_baseline(mod_file, cf_min) 
mod1c <- modify_baseline(mod_file, cf_median) 
mod1d <- modify_baseline(mod_file, cf_mean) 
base_pr <- get_XH(mod1c)$true_pr
data_file <- get_district_pfpr("Madi-Okollo District")

plot(mod1a$outputs$time/365+FirstYear, mod1a$outputs$orbits$XH[[1]]$true_pr, ylab = "PR",lwd=2, xlab = "Time", type = "l", ylim = c(0,1), col="darkred")
  lines(mod1b$outputs$time/365+FirstYear, mod1b$outputs$orbits$XH[[1]]$true_pr,  lwd=2, col="darkgreen")
  lines(mod1c$outputs$time/365+FirstYear, mod1c$outputs$orbits$XH[[1]]$true_pr, lwd=2,  col="purple4")
  lines(mod1d$outputs$time/365+FirstYear, mod1d$outputs$orbits$XH[[1]]$true_pr, lwd=2,  col="darkorange")
   lines(mod_file$outputs$time/365+FirstYear, mod_file$outputs$orbits$XH[[1]]$true_pr, lwd=2,  col="darkblue")
  
 # add_irs_history("Madi-Okollo District",col="blue",2015)
  segments(FirstYear + 2861/365, 0, FirstYear+2861/365, 1, lwd= 2,col = "darkred")
  segments(FirstYear + 3256/365, 0, FirstYear + 3256/365, 1,lwd=2, col = "darkred")
  segments(FirstYear + 3622/365, 0, FirstYear + 3622/365, 1,lwd=2, col = "darkred")
  with(data_file, lines(jdate/365+FirstYear, pfpr, pch=16,type = "o", col="darkblue"))
# par(xpd = TRUE, mar = c(5, 4, 4, 2))  # allow plotting outside
# legend("bottom",    inset=-0.2 ,              # Position of the legend
# legend = c("fitted model", "irs effect size","baseline","obs_pr"), # Names for the groups
# col = c("green", "red","purple","darkblue"),
# lwd=2, pch=c(NA,NA,NA,16), horiz = TRUE, bty="n")      # Colors corresponding to the groups
             # Symbols for the groups





# xds_plot_PR(mod_file, clrs="darkblue")
# xds_plot_PR(mod1a, clrs = "darkred", add=TRUE)
# xds_plot_PR(mod1b, clrs = "darkgreen", add=TRUE)
# xds_plot_PR(mod1c, clrs = "purple4", add=TRUE)
# xds_plot_PR(mod1d, clrs = "darkorange", add=TRUE)
# segments(2861, 0, 2861, 1, col = "darkred")
# segments(3256, 0, 3256, 1, col = "darkred")
# segments(3622, 0, 3622, 1, col = "darkred")
# lines(data_list[[92]]$times, data_list[[92]]$pr, col = "darkblue", type = "b", pch=15)
```
```{r}
#effect_size
max_eff <- mod1a$outputs$orbits$XH[[1]]$true_pr
min_eff <- mod1b$outputs$orbits$XH[[1]]$true_pr
median_eff <- mod1c$outputs$orbits$XH[[1]]$true_pr
mean_eff <- mod1d$outputs$orbits$XH[[1]]$true_pr

max_effless <- max_eff[1:(length(max_eff) - 3)]/mod_file$outputs$orbits$XH[[1]]$true_pr
min_effless <- min_eff[1:(length(min_eff) - 3)]/mod_file$outputs$orbits$XH[[1]]$true_pr
median_effless <- median_eff[1:(length(median_eff) - 3)]/mod_file$outputs$orbits$XH[[1]]$true_pr
mean_effless <- mean_eff[1:(length(mean_eff) - 3)]/mod_file$outputs$orbits$XH[[1]]$true_pr

plot(mod_file$outputs$time/365+FirstYear,max_effless, type= "l",lwd= 2, col="darkred" , xlab = "Time", ylab = "Effect Sizes" )
lines(mod_file$outputs$time/365+FirstYear,min_effless , lwd= 2, col="darkgreen")
lines(mod_file$outputs$time/365+FirstYear,median_effless, lwd= 2, col="purple4" )
lines(mod_file$outputs$time/365+FirstYear,mean_effless, lwd= 2, col="darkorange" )

segments(FirstYear + 2861/365, 0, FirstYear+2861/365, 5, lwd= 2,col = "darkblue")
segments(FirstYear + 3256/365, 0, FirstYear + 3256/365, 5,lwd=2, col = "darkblue")
segments(FirstYear + 3622/365, 0, FirstYear + 3622/365, 5,lwd=2, col = "darkblue")

legend("topleft",    #inset=-0.2 ,              # Position of the legend
legend = c("max", "min","median","mean"), # Names for the groups
col = c("darkred", "darkgreen","purple4","darkorange"),
lwd=2, pch=c(NA,NA,NA,NA,16), horiz = FALSE, bty="n")      # Colors corresponding to the groups
             # Symbols for the groups

```


```{r, fig.height=8, fig.width=11}
profile_plot(mod_file, get_district_pfpr("Madi-Okollo District"))
```

```{r}
#devtools::load_all()
abim_mod_file$EIRpar$trend_par$tt
```

```{r, fig.width=8, fig.height=7}
png("../outputs/tororo.png", width=720, height=600)
filename <- paste(box_dir, "/models/tororo_district_eir_sis.rds", sep="")
tororo_mod_file <- readRDS(filename)
data <- get_district_pfpr("Tororo District")
profile_plot(tororo_mod_file, data, 2015)
dev.off(dev.cur())
```

```{r, fig.width=8, fig.height=7}
i=92
district <- district_dir[i,1]
dir <- district_dir[i,2]
filename <- paste(box_dir, "models/", dir, "_eir_sis.rds", sep="")
model <- readRDS(filename)
data <- get_district_pfpr(district)
mod_name = paste(website_dir, dir, "/", dir, "_eir.png", sep="")
profile_plot(model, data, 2015)
```

```{r}

```

```{r, eval=F}
for(i in 1:146){
  district <- district_dir[i,1]
  dir <- district_dir[i,2]
  filename <- paste(box_dir, "Models/", dir, "_eir_sis.rds", sep="")
  model <- readRDS(filename)
  data <- get_district_pfpr(district)
  mod_name = paste(website_dir, "/", dir, "_eir.png", sep="")
  png(mod_name, width=720, height=600)
  profile_plot(model, data, 2015)
  dev.off(dev.cur())
}
```
